version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
  app:
    image: ghcr.io/christophetd/log4shell-vulnerable-app:latest

