language: go
go:
  - 1.7
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - tip

before_script:
  - go get -v github.com/akavel/rsrc

matrix:
  allow_failures:
    - go: tip  

script:
  - go vet $(go list ./... | grep -v /vendor/)
  - go test $(go list ./... | grep -v /vendor/)
  - make
